[functions.exchange-garmin-token]
    enabled = true
    verify_jwt = false
    import_map = "./functions/exchange-garmin-token/deno.json"
    entrypoint = "./functions/exchange-garmin-token/index.ts"